ellisonleao/magictools

README.md
1. I changed Paradox3D to Xenko 'cause the latter is the new name.
2. I don't know if it is proper to correct the spelling in this file (from "open soucce" to "open source"), since it's a big change on 38 lines. If it's not proper, I'll create a new pull request without this commit.
=> Change Paradox3D to Xenko

README.md
README.md has duplicated 'music and audio editors' session. This PR removes the duplicated session.
=> remove duplicated 'music and audio editors' session

README.md
Google Poly seems like a nice UI for searching for 3D models. It's a bit annoying because you have to change the search options to remixable to find ones you can download. Models seem to all be OBJ files.
Seems to compare favourably in user experience to other options (blender-models requires facebook likes to download, Yobi3D has several steps to find download links on other websites). But selection is probably worse (best content seems to be provided by Google).
=> Add Google Poly

README.md
The link is outdated, pointing to the old google code repo
=> Update JitterPhysics to new repo

README.md
`EnTT` started as a fast ECS in C++ a while ago and now is getting a general purpose framework for game development. It's used also by Mojang in Minecraft (bedrock), link on the README. This is why I think it's worth adding it to this list.  
It has a MIT license.
=> Added EnTT to the list of frameworks

README.md
OpenXRay is a community-modified X-Ray engine used in S.T.A.L.K.E.R. game series. It's free for non-commercial use.
=> Add OpenXRay engine

README.md
Accuracy. I made a typo in the last PR.
Cross platform graphics for high performance **graphics**.
_to_
Cross platform graphics for high performance **games**.
=> Typo graphics -> games in description (heaps)

README.md
Monkey X has been discontinued. There is a rebranded open-source fork called Cerberus X. The same company which released Monkey X (Blitz Research Ltd) has released Monkey2.
=> Replace "Monkey X" with "Cerberus X" and "Monkey2"

README.md
This PR updates Ebiten's URL to https://ebiten.org/
=> Update Ebiten's URL

README.md
The LITIengine is a free and open-source 2D Java  Game engine. It particularly targets beginner-level game developers due to its plain Java nature.
Does this project have any License?
It's licensed under the MIT License.
=> Add the LITIengine to the list of engines and frameworks

README.md
MagicaVoxel is not Open Source. See their license on the home page:
https://ephtracy.github.io/index.html?page=mv_main
License
Free to use for any project
Credits to the software are appreciated (e.g. "created by MagicaVoxel")
Selling the software (original or modified) is disallowed
=> Fix MagicaVoxel is not Open Source but free to use

README.md
Matcaps - A wide variety of Matcaps textures
ecs-lib - An Entity Component System (ECS) library in typescript
They are two important libraries for game development.
ecs-lib - https://github.com/nidorx/ecs-lib#license
Matcaps https://github.com/nidorx/matcaps#license
=> Added Matcaps and ecs-lib libraries

README.md
Here is the github of the project:
https://github.com/piskelapp/piskel
It's already on the list
It's licensed under Apache 2.0
=> Changing Piskel to be presented as open source

README.md
raylib is an excellent library for videogames programming with a very straightforward approach and tons of language bindings. It's ideal for programming novices, but - since it's written in plain C - is also perfectly feasible for larger project sizes.
raylib allows for multiplatform (including Windows, Linux, MacOS, Android and HTML5) 2D and 3D game development and provides functions for Font rendering, Animated 3D models, Textures, Shaders, Audio and even VR stereo rendering.
Aside from C and C++, raylib can also be used with C#, Go, Python, Rust, Node.js and many more due to a plethora of language bindings (see: https://github.com/raysan5/raylib/blob/master/BINDINGS.md).
I have no personal affiliation with the project, I'm …
=> Add raylib as an open source game engine

README.md
MakeHuman official page has moved.
13 May 2018
Makehuman.org IS NO LONGER the official page of makehuman project.
The new official page is makehumancommunity.org
The new official page of MakeHuman project is www.makehumancommunity.org, a great site maintained by the MH community that includes many services and tools: MakeHuman development, forum, bugtracker, FAQ, documentation and more.
=> fix MakeHuman URL

README.md
Blitz 3D is an open source game engine, it has been released under the zlib license as seen on its github repo. https://github.com/blitz-research/blitz3d
The link is already on the list, it's just not marked as open source when it is.
Blitz3D is under the zlib license.
=> Mark Blitz3D as open source

README.md
It is the correct one, and the current link sends you to a sketchy website unaffiliated with the Blitz3D project. The developer of Blitz stopped hosting that website a while back. I didn't realize the link was wrong until now.
=> Change dead Blitz3D link to point to current github repo

README.md
Common 3D modeling software is almost focus on low-ploy modeling. But ZBrush is professional in high-poly modeling. And Normal Map is now frequently used in 3D game industry. However, Normal Map is generated by projecting the geometrical details from  high-poly model to low-poly model. So ZBrush is a important modeling tools.
ZBrush is a commercial software need to pay for it.
=> Add ZBrush in part of Modeling tools

README.md
Closes #243
As stated in #243, ÖbEngine is free modern C++ game engine on top of the SFML 2.5.1, using Lua as its scripting language, working on Windows, Linux and MacOS.
It's sponsored by a few big companies such as JetBrain, DigitalOcean and GitHub, just so you know it's not another project which will go under water in 2 weeks.
It's under the [MIT licence](https://github.com/Sygmei/ObEngine/blob/master/license)
=> Adding ÖbEngine

README.md
I'm submitting my tool because I've found it very useful in game-related work I've done. Basically everything in it was created to make my life easier and I think anyone who needs separate files and finds it easier to draw in a larger tilesheet will get a lot out of using it. I've helped a few people use it so far. They were going to export each texture in it one by one and were really happy to know they could do it in a much faster/easier way. Hopefully some other people can get something out of it too.
I wasn't sure if it had one because I have a bad habit of not putting licenses on stuff and procrastinating doing something about that, but I checked and it is listed as MIT.
There's documentation for nearly all of it as well.
An example of its efficacy for a very repetitive tilesheet, I …
=> add another spritesheet tool

README.md
Solarus is a small but old game engine (10 years in the making! I feel old) with a supportive and active community, and some professionally-released games (Steam, GoG).
This project is released under GNU GPL v3 license, and the included resources are also free (CC-BY-SA 4.0, MIT).
=> Add Solarus game engine

README.md
https://stride3d.net/blog/xenko-has-been-renamed-to-stride/
=> Rename Xenko to Stride

README.md
This tool provides a powerful UNIT testing capability that has not existed in NES console(MOS 6502) development environment until now.
MIT
=> Add 6502 Unit Test executor

README.md
- https://github.com/ikpil/DotRecast
DotRecast is a port of Recast & Detour, a navigation mesh toolset for games, to the C# language. It is useful for game developers who want to use C# servers, C# projects, or Unity3D for their games.
DotRecast allows you to generate and use navigation meshes for pathfinding and spatial reasoning in your game world. You can also customize the navmesh generation and runtime navigation systems to suit your specific game’s needs.
https://opensource.org/license/zlib
=> Add DotRecast to Engines and Frameworks section

README.md
The project ceased in 2022 and the domain has been taken over by a placeholder.
=> Remove Amethyst

README.md
MapperMate is the only cloud-based map editor in existence from what I'm aware of today. Users can easily create stunning game maps, then come back to them at any time, on any machine, anywhere.
All features are completely free for a user's first map, so they can create a full game or something exquisite without ever worrying about payments.
No license
=> Add MapperMate as a Tile / Level Editor
