- README.md
Twine is a great little game development tool used to create Choose-Your-Own-Adventure stories. It makes it easy to create branched narratives, and games can be styled with CSS and played online.
> Update README: add Twine to the list

- README.md
Android OpenGL ES 2.0/3.0 Engine
> Add Rajawali

- README.md
Epic games released unreal engine 4 for free.
It's just a most complete and updated UDK.
> Replace UDK with Unreal Engine 4

- README.md
> Update README - Added Lums

- README.md
For https://github.com/ellisonleao/magictools/issues/63
> Add `awesome-gametalks`

- README.md
Gunpoint-3D and Openstock Project no longer work.
> Remove two broken links from graphics section.

- README.md
PICO-8 is a fantasy console for making, sharing and playing tiny games and other computer programs.
> Add PICO-8 fantasy console

- README.md
Added iio.js
https://github.com/iioinc/iio.js
http://iio.js.org/
> Add iio.js

- README.md
Added [Coquette](http://coquette.maryrosecook.com/). A 2D Framework for JS games.
> Add Coquette

- README.md
`http://haxor.thelaborat.org/` is deprecated.
> Update Haxor 3D Engine site

- README.md
Add another resource I found the today.
> Add gamesounds.xyz

- .travis.yml
- README.md
Looks like the syntax for white list was wrong.. also reviewed the build and looks like it did not apply
However added new items to white list
- qiciengine
- gamesalad 
- thebloomapp
Looks like http://enchantjs.com/ is down at the moment.. should be a temporary issue
> Fix Travis Build 

- README.md
They recently started using github and this is a great engine to use so it would make a great addition to this list
> Added in CRYENGINE to 3D game engine

- README.md
* Fixed syntax on hacknplan url
* Added one hour game jam - Weekly one hour game jam 
* Added description on current game jams
* Added Superpowers 2D/3D Game Engine - HTML5 Collaborative 2D/3D Game Maker
* Added ChipTone - Online sound effect generator 
* Added Oryx Design Lab - Cheap high quality royalty free sprites (well worth it) 
* Added Twitch GameDev - It's twitch duh 
* Added Fracplanet - Fractal planet and terrain generator
* Added Gif2TileSet - Coverts GIFs into spritesheet
* Added Libgdx Texture Packer - Texture Packer built into Libgdx
* Added Cheetah-Texture-Packer - High efficient and fast 2D bin packing tool
* Added Kenny Assets - Royalty free assets
* Added Casual - Visual Project Management
* Added Taiga.io - Project management platform for agile developers & designers
* …
> Added GameJam, Engine, Twitch, Assets, Other tools

- README.md
PR for #95 
I changed Godot description and added the engine to 2D category.
I don't know if an engine can be included in both categories...
> Change Godot description and add to 2D category

- README.md
Added the TIC - Tiny Computer Game Engine
> Added TIC Game Engine, SunVox, And Alphabetized Music Section

- README.md
> Add GitHub Game Off to Game Jam section

- README.md
Awesome tool, I use it all the time.
> Added Bosca Ceoil by Terry Cavanagh

- README.md
Codecks is a project management tool intended for game developers, so I guess it might be a good fit for this list :)
I wasn't quite sure whether to mark it as "commercial" or "limited free". You'll get credited 50€ for free and then pay 8€ per user/month. So in a way it's free, on the other hand it's *quite* limited. Happy to change the label to "commercial" if you feel this describes the case more accurately!
> Add Codecks as Project Management Tool

- README.md
Added some links of pixel art editors which are mainly covers 8-bit computers like the Commodore 64, ZX Spectrum etc. Also added a link to relative new multi purpose pixel art editor.
> Added new pixel art editor links

- README.md
Graphics\Spritesheet Tool\Sprite Sheet Packer
> Graphics\Spritesheet Tool\Sprite Sheet Packer

- README.md
And add a video/podcasts link on the content index.
> Add Chinese language edition link

- README.md
Online free tutorial book which Pygame official site recommends.
>  Added Making Games with Python & Pygame

- README.md
I accidentally made the fork of a fork, so I figured I can contribute here as well since that fork seems to be a bit stale. Not stale enough to provide merge conflicts fortunately. :)
Added MilkyTracker as it's one of the few trackers available for macOS (and open source at that), so I think it's worth it.
I see there's also one minor change with trailing space elsewhere in the file, sorry about that - my editor did it automatically on saving the file, I can remove it if it bothers anyone :)
> Add MilkyTracker

- README.md
Added a nice behaviour tree library for C#
> Added Fluent Behaviour Tree

- README.md
This bestselling and highly recommended book (check both [Amazon](https://www.amazon.com/Unity-Action-Multiplatform-Game-Development/dp/161729232X/) and [Goodreads](https://www.goodreads.com/book/show/23816485-unity-in-action)) teaches you to write and deploy games with the Unity game development platform.
> added book Unity in Action

- README.md
Details in [this](http://esotericsoftware.com/support#Spine-FAQ).
> Added commercial license legend for Spine.

- README.md
> Why do you think the link is worth adding on this list?
Ebiten is mature enough to develop 2D games (I believe :-) (e.g. http://blockbros.net/tsugunai/ is developed with Ebiten)
> Does this project has any License?
Apache License 2.0
> Add Ebiten

- README.md
> Add NetHack to Complete Game Sources list

- README.md
> Add Canabalt iOS to Complete Game Sources list

- README.md
Hi Ellison, I've added the pull request for spritemate.com
Cheers!
> added spritemate link

- README.md
Added modo in to 3d modelling list because it is one of the most magical 3d tools you can find :) It's cheap and has an inexpensive subscription plan
You must purchase a perpetual or subscription based license
> Added modo

- README.md
> Pixen is no longer free/open source

- README.md
Its a useful commercial tool, and got very good responses you can see here https://www.reddit.com/r/gamedev/comments/7ylvt9/pixelator_a_gamedev_tool_i_wrote_to_convert_any/
Yes, its free for non commercial, and there's a paid studio / company licenses (one-time payment).
> Added Pixelator tool

- README.md
Cross-Platform framework/development tool for making 2D/3D games with Lua/LuaJIT, compatible iOS, Android, Mac and Windows devices.
Could be useful for game developers
Free with no warranty, as is.
> LuaStudio app

- README.md
- README_ch.md
[REXPaint](https://www.gridsagegames.com/rexpaint/) is a powerful and elegant tool made by [Grid Sage Games](https://www.gridsagegames.com/), also it is used to make [Cogmind](https://www.gridsagegames.com/cogmind/index.html)
**Does this project has any License?**
Not found
> add REXPaint

- README.md
- README_ch.md
[Amulet](http://www.amulet.xyz/) is a great tool created by Ian MacLarty
**Does this project has any License?**
Yes, [here](https://raw.githubusercontent.com/ianmaclarty/amulet/master/LICENSE)
> add amulet

- README.md
added Live Normal to Texture Tools
Its a free tool for game developers
Free without restriction.
> added Live Normal

- README.md
As discussed in [Issue 178](https://github.com/ellisonleao/magictools/issues/178). Thank you!
> Add Juno to README.md

- README.md
An excellent tool for an excellent list.  Thanks for putting this together.
> Add a link to tilemancer under image editors.

- README.md
Diligent Engine is an open-source low-level graphics library that facilitates development of applications that require high-performance 2D/3D rendering
Apache 2.0
> Added link to Diligent Engine

- README.md
Dual-license MIT/Apache-2.0
https://github.com/amethyst/amethyst
https://crates.io/crates/amethyst
> Mark Amethyst as open-source

- README.md
It's an open source engine that can help Swift programmers easily start making 2d games on their native platform
It is licensed under MIT License.
> Add glide engine

- README.md
https://github.com/phoboslab/impact
It's correcting inaccurate information.
MIT
> ImpactJS is open source since May 2018

- README.md
Hey! I'd like to propose you to add another link to this awesome list.
[OpenTTD](https://github.com/OpenTTD/OpenTTD) is a great example of open source game being carefully maintained and developed by community of volunteers for more than 14 years.
GNU General Public License v2.0
> docs: add OpenTTD as an open source game

- README.md
- Why do you think the link is worth adding on this list?
Phina.js is a nice web game framework. The documentation is mostly in Japanese, but its API is very user friendly, so it's easy to work with.
The description was translated from *"ゲームやツールを<ruby>簡単<rt>かんたん</rt></ruby>に<ruby>作<rt>つく</rt></ruby>る<ruby>事<rt>こと</rt></ruby>ができる JavaScript ゲームライブラリだよ"*.
- Does this project has any License?
Yes, it's [MIT-licensed](https://github.com/phinajs/phina.js/blob/develop/LICENSE.txt).
> Add phina.js game framework

- README.md
I used this recently in one of my game prototypes.
https://www.mixamo.com/#/
its really only good for humanoid models. but there are a lot of nice animation included for free
I dont believe there is for  the free version. but there is one for t he paid version
> Added mixamo 3d animation and rigging tool

- README.md
The guy wrote an engine in Kotlin by almost himself including api for 2d, 3d graphics, sounds, physics
Apache License 2.0
> add KorGE kotlin game engine

- README.md
Book: Learn OpenGL: Beginner's guide to 3D rendering and game development with OpenGL and C++
I read the book a half year ago and my game development skills increased rapidly. The book contains exercises for every level so you can start at any point.
It is a book you need to buy.
> Added Learn OpenGL to Books section

- README.md
Greetings, I've personally been working on a project that aims to be a fully-featured body of knowledge on developing games. The project already features pseudocode and python listings and is open to many more.
The project is not complete and in continuous evolution, hopefully it's worth being on this list.
The project takes form of a PDF artifact downloadable from the page, so I added it to the "books" section, hopefully it's in the right place.
*Update:* I put only the gitlab link on the repository, but there is a github mirror too, if it's more fitting: https://github.com/Penaz91/2DGD_F0TH
**Does this project has any License?**
The entire project is licensed under Creative Commons Attribution-Non Commercial 4.0 License.
Thank …
> Added 2D Game Development - from zero to hero

- README.md
> Why do you think the link is worth adding on this list?
We built [Nakama](https://github.com/heroiclabs/nakama) to help game developers and studios build server-based games on desktop, mobile, and web. With Nakama server you can add user authentication, social networking, cloud storage, realtime data exchange, and lots more into games. It is developed to handle the difficult but essential services that go into all social and realtime games.
> Does this project has any License?
The project is licensed under the [Apache-2 License](https://github.com/heroiclabs/nakama/blob/master/LICENSE). You can find it referenced on the [GitHub project](https://github.com/heroiclabs/nakama#license).
> Add Nakama to the game development resources list.

- README.md
> Why do you think the link is worth adding on this list?
3D Game Shaders For Beginners is a free step-by-step guide on how to implement SSAO, depth of field, lighting, normal mapping, and more for your 3D game. 
> Does this project has any License?
The license for the source code is [BSD 3-Clause License](https://github.com/lettier/3d-game-shaders-for-beginners/blob/master/LICENSE).
> Adds 3D Game Shaders For Beginners.

- README.md
IMHO High Quality Textures with additional maps for free.
CC0
> Added TextureHaven

- README.md
Thanks @ellisonleao  !
It can generate terrain assets within seconds from real data (see gallery here : https://sketchfab.com/xfischer/models)
Same as Unity : free for individual and <100K$ gross revenue companies
> Add elevationapi as Terrain generators and code

- README.md
> Changed Elevation API from free to open source

- README.md
I believe that this provides game devs the ability to quickly and easily add speech content within their games.
This is a paid service with a freemium model to try. All paid users can use their assets commercially.
> adding Resemble

- README.md
With 2.7k stars and a sprawling community, Flame has become a cornerstone of Flutter game development.
Yes, MIT (open source)
https://github.com/flame-engine/flame/blob/master/LICENSE
> Add Flame to game engines

- README.md
This patch adds the Open Source license legend to Grid and updates its
description.
Thank you for including us in this list!
\- Planimeter
> Update Grid Engine

- README.md
Project management Codecks: 0$ up to 3 users and 5 projects.
💰 --> 💸
It is already in the list
Now partially free...
> Codecks:  Now free for small teams

- README.md
Astera is an easy to use cross platform C99 Game Library / Framework. 
Features: 
```
Cross Platform: Supports Windows, Linux, Mac OSX, and FreeBSD
Rendering
Batched 2D Rendering
Baked Sheet (Tiled or Bounded boxes)
Post Processing Effects
Custom Particle Simulation 
Vector Graphics based User Interface
Supports programmatic input (aka controllers, mouse, keyboard, etc)
Audio
3D Audio
Quick Sound Effect playback (OGG Vorbis & WAV)
Song / Stream playback
Assets
ZIP & PAK File Management
General asset management
```
Yes, the MIT License, reference: https://tek256.com/astera/LICENSE.html
> Add Astera to Game Engines / Frameworks

- README.md
* _Why do you think the link is worth adding on this list?_
The project has been in constant development since 2011 and I think it can be a worthy addition to this awesome list.
For more information, like features and screenshots, you can have a look at the [website](https://ncine.github.io/).
* _Does this project has any License?_
The project is licensed under the MIT License.
> Add nCine to the list of engines and frameworks

- README.md
Gorgon is a modular set of APIs written in C#. It has support for virtual file systems, user input, basic graphics functionality and more fleshed out 2D rendering utilizing Direct 3D 11.2.
Yes, it is open source, licensed under the MIT license.
> Add Gorgon

- README.md
Why do you think the link is worth adding to this list?
Many popular games use this.
I have used it.
It's worth a mention.
Its described here https://github.com/BabylonJS/Babylon.js/blob/master/license.md
It's an Apache License 2.0
> added Babylon.js

- README.md
This is a great book about game design from the Creator of RimWorld.
I'm not sure.. this is a paid book.
> Add Designing Games by Tynan Sylvester

- README.md
Hi, libgdx community have create a website at https://libgdx.com/.
github repo : [https://github.com/libgdx/libgdx.github.io](url)
> Update libGDX uri

- README.md
It's a FOSS alternative to Aseprite, the most popular tool in its niche.
GPL
> Added LibreSprite

- README.md
> Update README.md (add Mini Micro to tools/frameworks)

- README.md
boardgame.io is a popular JS game engine with over 8k stars on GitHub.
MIT
> Add boardgame.io

- README.md
> Rename Corona SDK to Solar2D

- README.md
This is a detailed tool for game design and generation that bridges ideas from UI/UX design with board game design for a different type of designing than other tools.
No
> Iterary Addition to list

- README.md
This sprite sheet tool has features the others do not:
- Supports animated GIFs
- Sprite pivot points
- Multiple export formats
GNU GPL3
> add `EzSpriteSheet`

- README.md
- Pyxel is a wonderful retro game engine for Python. The documentation has been translated into several languages!
- Available from PyPI: https://pypi.org/project/pyxel/
- MIT License as seen in https://github.com/kitao/pyxel
> Adding Pyxel

- README.md
Hi,
Stjepan from Mannig here. I thought this title might be a good match for your list. Thank you for considering it.
Best,
> Added Geometry for Programmers

- README.md
> Fixed Construct License Emoji

- README.md
SpriteKit is there but SceneKit is missing. Furthermore, the description for SpriteKit is unaccurate.
> Added SceneKit and updated SpriteKit's description

- README.md
Node VFX editor for pixel art
- Really cool pixel VFX editor
- Open Source
- Active development
MIT
> Add Pixel Composer

- README.md
Procedural texture creator
- Great alternative to substance designer
- Free and open source
MIT
> Add Material Maker

- README.md
Physics based 3D character animation
- Has a free tier with very generous use
- Fun to use
- Need to credit Cascadeur. More info at [Cascadeur end-user agreement](https://cascadeur.com/help/cascadeur_end_user_agreement)
> Add Cascadeur

- README.md
> Fix :tada: typo

- README.md
This list was missing a small simple physics engine
CC0 1.0 public domain
> Add tiny physics engine

- README.md
OpenRA is a mature project with complete code availability. I realize it already exists in a different spot on this list, so if that disqualifies this PR feel free to reject with no hard feelings here.
GPL3
> Add OpenRA to Complete Game Sources

- README.md
It can be useful for quick prototyping pixel art concept games or getting a pixel art starting point from any image.
No
> Add Pixelicious, free image-to-Pixel Art ⚔️

- README.md
It's a totally free and open source engine written in pure TypeScript. It can teach a lot about generics and engine development to people who are starting out in both the TS and gamedev spaces.
MIT
> Add asimov-ts

- README.md
Alphabetically organized the modeling topic
Added more 3D software to the modeling topic
And the corrected version of sculptris with the new alternative versions of the original
> Added more 3D software to the modeling topic

- README.md
As asked in issue #300 I included some of the most known game dev communities, some of them may contain many resources on YT that could hep newcomer devs to learn.
No.
> Added a section containing some of the most known Game Dev Communities

- README.md
Flax is open-source but you pay royalties when you reach a threshold - thus both labels
It is decently popular and production-ready.
Flax Engine End User License Agreement
> add Flax Engine

- README.md
Changed GameMaker license icon to partially free - as it's free for non-commercial work since Nov 2023.
source: https://twitter.com/GameMakerEngine/status/1726949064196128776
> GameMaker license update

- README.md
(Disclosure: I am the developer of Lightcube) Lightcube offers a number of unique features including:
- Import Photoshop PSD files
- Isometric shape tool
- Built-in pattern brushes (for things like brickwork, landscapes, fences, windows, doors, meshes etc., stuff that's painstaking to draw)
- Color ramp generator with configurable hue shifting
- Inline text tool
Lightcube is closed source and requires a license purchase.
> Added Lightcube Pixel Art Editor

- README.md
> Added Supernova Engine

- README.md
Added SnowB Bitmap Font Generator
> Added SnowB Bitmap Font Generator

- README.md
I added my own blog, which is dedicated to teaching video game development. It has tons of tutorials for  making different mechanics and complete games.
Its free.
> Added gameidea.org under blogs

- README.md
Have put in over 300 hours to create almost 100 hours worth of comprehensive game dev courses across the site. About 95% of the courses are free and contain Creative Commons Zero (CC0) licensed content with GitHub source code sectioned out by video chapter so developers can follow along 1-to-1 with each tutorial.
No license. Assets contained in courses are all CC0.
> feat: chris courses to learn section
